Update bundler in travis for 1.9.3 bundler bug
Without this change, testing 1.9.3 in travis results in the following
message:

    NoMethodError: undefined method `spec' for nil:NilClass

This seems to be related to the specific version of bundler that is
being used in travis for the 1.9.3 ruby only.